root = "/app"
tmp_dir = "/tmp"

[build]
  bin = "/tmp/main"
  cmd = "go build -o /tmp/main ./cmd/api"
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
  exclude_regex = ["_test.go"]
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  send_interrupt = true
  delay = 1000

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[screen]
  clear_on_rebuild = true
